### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by dakaneye** [dakaneye/test#1]
```
details:
  msg: Never give a sword to a man who can't dance - Confucius
id: eb60bbcc22774d129274ea1dc96dbb42
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://localdev-anchore-engine-api:8668
  hostid: localdev-anchore-engine-api-7d5dd9fc6d-97rxr
  request_id: null
  servicename: notifications
timestamp: '2021-01-27T17:25:36.897659'
type: system.test.random_wisdom
```
